name: Awesome Inc
description: Create and grow high tech startups
permalink: pretty
relative_permalinks: false
include: [_data]
sass:
  sass_dir: _scss
  # style: compressed
gems:
  - jekyll-sitemap
  - jekyll-redirect-from
exclude:
  - node_modules